.\" Manpage for ProCalc.
.\" Contact anton2920@gmail.com for comments or help.
.TH man 1 "06 Apr 2019" "1.0" "STL man page"
.SH NAME
STL
.SH SYNOPSIS
STL states for Standard Template Library
.SH DESCRIPTION
The Standard Template Library (STL) is a software library for the C programming language. 
It provides four components called algorithms, containers, functions, and iterators.
.SH OPTIONS
STL is a library and does not take any arguments.
.SH BUGS
No known bugs.
.SH AUTHOR
Pavlovsky Anton (c) 2019 (anton2920@gmail.com)
